 @define-color foreground #B2ABAA66;
 @define-color background #0C050466;
 @define-color background-alt rgba(12,5,4,0.25);
 @define-color cursor #B88E8366;
 
 @define-color color0 #4B453766;
 @define-color color1 #1A0B0966;
 @define-color color2 #462D0866;
 @define-color color3 #5A292466;
 @define-color color4 #78465766;
 @define-color color5 #8E554566;
 @define-color color6 #B3897066;
 @define-color color7 #897F7D66;
 @define-color color8 #60595866;
 @define-color color9 #230F0C66;
 @define-color color10 #5D3C0B66;
 @define-color color11 #78363066;
 @define-color color12 #A05D7466;
 @define-color color13 #BE715C66;
 @define-color color14 #EFB79666;
 @define-color color15 #897F7D66; 
