[colors.primary]
background = '#121410'
foreground = '#e3e3db'
 
[colors.cursor]
text = '#e3e3db'
cursor = '#c5c8ba' 
 
[colors.vi_mode_cursor]
text = '#121410'
cursor = '#a9d473' 
 
[colors.search.matches]
foreground = '#44483d' 
background = '#a0d0cb' 
 
[colors.search.focused_match]
foreground = '#44483d' 
background = '#a9d473' 
 
[colors.footer_bar]
foreground = '#44483d' 
background = '#e3e3db' 
 
[colors.hints.start]
foreground = '#44483d' 
background = '#c0cbac' 
 
[colors.hints.end]
foreground = '#44483d' 
background = '#c0cbac' 
 
[colors.selection]
text = '#121410'
background = '#a9d473'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#a9d473' 
yellow = '#446813' 
blue = '#a9d473' 
magenta = '#a0d0cb' 
cyan = '#c0cbac' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 