[config]
# ...

caching = false

[templates.niri]
input_path = '/home/vic/.config/matugen/templates/niri.kdl'
output_path = '~/.config/niri/user/decorations.kdl'
post_hook = 'niri msg action load-config-file'

[templates.gtk3]
input_path = '/home/vic/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-3.0/gtk.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}} && nautilus -q'

[templates.gtk4]
input_path = '/home/vic/.config/matugen/templates/gtk-colors.css'
output_path = '~/.config/gtk-4.0/gtk.css'
post_hook = 'cp ~/.config/gtk-4.0/gtk.css ~/.config/gtk-4.0/gtk-dark.css'

[templates.rofi]
input_path = '/home/vic/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

[templates.waybar]
input_path = '/home/vic/.config/matugen/templates/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.wlogout]
input_path = '/home/vic/.config/matugen/templates/colors.css'
output_path = '~/.config/wlogout/colors.css'

[templates.pywalfox]
input_path = '/home/vic/.config/matugen/templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'

[templates.color-scheme]
input_path = '~/.config/matugen/templates/Matugen.colors'
output_path = '~/.local/share/color-schemes/Matugen.colors'

[templates.qt5ct]
input_path = '/home/vic/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'

[templates.qt6ct]
input_path = '/home/vic/.config/matugen/templates/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.cava]
input_path = '/home/vic/.config/matugen/templates/cava.ini'
output_path = '~/.config/cava/themes/matugen'

[templates.alacritty]
input_path = '/home/vic/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'

