general {
    ignore_dbus_inhibit = false
    lock_cmd = pidof hyprlock || hyprlock
  }

listener {
    timeout = 540                     # 9 min
    on-timeout = notify-send  " You are idle!" # command to run when timeout has passed
    on-resume = notify-send  " Oh! you're Back" " Hello !!!"  # command to run when activity is detected after timeout has fired.
}

# Screenlock
listener {
    timeout = 600                     # 10 min
    on-timeout = loginctl lock-session
    on-resume = notify-send " System Unlocked!"  
}
